### PR TITLE
attempt to get data

### PR DESCRIPTION
**Pull request by dzheng256**

### CODE REVIEW

**Comment by vonbearshark** [comment]
Is this for #52 ?

**Comment by dzheng256** [comment]
yea

**Review by RitwikGupta — COMMENTED** [review]
`flatten()` isn't a function that exists, throws an error

**Review by RitwikGupta — CHANGES_REQUESTED** [review]
See if you can rewrite using [urllib3](https://urllib3.readthedocs.io/en/latest/)
Also, please put all of this into a directory called `ml` with a subdirectory called `data` where the data is stored.

**Comment by dzheng256** [comment]
Oops, it works without that line..

**Comment by dzheng256** [comment]
made some changes, works now with requests, attempting to get urllib3 working but it's losing all the actual data for some reason

**Comment by RitwikGupta** [comment]
```python
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', 'https://data.wprdc.org/api/action/datastore_search', fields={"resource_id": "40776043-ad00-40f5-9dc8-1fde865ff571", "q": "oakland"})
data = r.data

# Write data to file
```

**Comment by dzheng256** [comment]
thanks, fixed

**Review by RitwikGupta — CHANGES_REQUESTED** [review]
No, don't put the source inside the data folder.
Also, replace data.txt with data.json

clubdata.py
--data
----data.json

**Comment by dzheng256** [comment]
fixed, again :P

**Review by RitwikGupta — APPROVED** [review]

**Pull request merged**
