### PR TITLE
Revert "Updated data notification"

### PR DESCRIPTION
**Pull request by vonbearshark**
Reverts Pitt-CSC/PantherView#121.

Code looks good, but it errors out in live. Something is undefined

### CODE REVIEW

**Comment by vonbearshark** [comment]
Sorry @seifriedc i must have jumped the gun. Let me know when you're finished. Code flow looks good

**Comment by CGS31** [comment]
Yeah I screwed up my merge conflict edit, shoulda let you know haha my bad. I have it fixed on my end so I'll push in a minute here. I wanted to ask you about the time ranges though - I thought it was a good idea. Say a dataset updates daily; within what range do you want to notify the user that the data has updated?

**Comment by vonbearshark** [comment]
What do you mean?

I think we should add a field to each dataset, like an `.updateTime` field, and we can choose a time that works for that dataset. So for hourly datasets, we want to make sure the change is maybe <10 min, and if it's a daily set, maybe it's <12 hours, or something

**Comment by seifriedc** [comment]
Ah I gotcha that makes sense. Yeah I was wondering what intervals you wanted. I'll work on that then. In the meantime I'll make a PR with the fix

**Pull request merged**
