### PR TITLE
Footer Added

### PR DESCRIPTION
**Pull request by ajfortuna97**
Added a basic footer that at the moment just contains some copyright information or if that needs to be changed, can also contain contact information. I've enclosed a picture of what it currently looks like with the pull request (footer in the bottom left). Also I added name to the Contributors list.

footer preview

### CODE REVIEW

**Review by RitwikGupta — CHANGES_REQUESTED** [review]
It would be better to style the footer from a stylesheet rather than inlining all of that (Line 22)

**Comment by ajfortuna97** [comment]
Alright. Would that be an edit in the main.css?

**Comment by RitwikGupta** [comment]
Yes it would! Just add the styles you had inline into a `footer` handle in the `main.css` file.

**Comment by ajfortuna97** [comment]
Alright, I'll fix that real quick.

**Comment by ajfortuna97** [comment]
Also, not too familiar with doing pull requests, so how do I "update" the request with the newly changed files again? Do I just submit a new pull request? I can't find the button on the site that say, allows me to changed what's pulled in.

**Comment by RitwikGupta** [comment]
When you make new changes, the PR is automatically updated!

**Review by RitwikGupta — APPROVED** [review]

**Comment by ajfortuna97** [comment]
Alright, thanks for the heads up on that!

**Pull request merged**
