### PR TITLE
Store records with null coordinates in separate array

### PR DESCRIPTION
**Pull request by mbilker**
This PR is a continuation on #61 to store coordinates in a separate array so something can be done with them later.

### CODE REVIEW

**Comment by vonbearshark** [comment]
I don't think this is the way we should go about this here. It's handy to have have one

**Review by vonbearshark — APPROVED** [review]
At first I thought this might not be a good way to go about this. There's a lot of benefits to having only one marker array (we only have to filter through one), but that would get complex with all the conditionals checking if it was a pin or a non-placed marker. So this is probably the best solution. FWIW, it's not just null location pins, it's also pins that just don't fall within Oakland.

**Comment by mbilker** [comment]
Alright, thank you. I know that some of the police ones are outside of Oakland because the original case was reported in Oakland, say for stolen vehicles.

**Comment by vonbearshark** [comment]
Right, we've been talking about this in #13 and #61 , and the consensus is that we want to limit the map view to _only_ Oakland (not even allowed to scroll to outside it), but we _also_ want to show the pins that originate outside Oakland. So we want to identify if a pin would be placed outside the Oakland bounding box we have, then place it with the pins that don't have any location given.

**Comment by mbilker** [comment]
How about `extraRecords` for the variable name?

**Comment by vonbearshark** [comment]
`nonPlacedRecords`?

**Comment by mbilker** [comment]
That sounds good.

**Pull request merged**
