### PR TITLE
Fixed data update notification variable

### PR DESCRIPTION
**Pull request by seifriedc**
Screwed up the last PR, my bad

### CODE REVIEW

**Comment by seifriedc** [comment]
Ah I'm getting another error, standby

**Comment by seifriedc** [comment]
Looks good now

**Comment by vonbearshark** [comment]
So it still looks like we're using the `range` constant versus adding a `range` (or whatever) property to the `WPRDC_DATA_SOURCES` objects--do you want to set that up in this PR?

**Comment by vonbearshark** [comment]
It otherwise looks good

**Comment by seifriedc** [comment]
Oh yeah I was gonna do that in a separate PR. I have it done though; I'll submit it today when I get a chance

**Comment by vonbearshark** [comment]
Awesome code--looks really slick. Looks like there's a conflict, but I'll be happy to merge it in after you fix the merge conflicts

**Comment by seifriedc** [comment]
Cool thanks!

**Pull request merged**
